name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Copy repository contents
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "."
        remote: quai-site
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}

    - name: Move files
      uses: fifsky/ssh-action@master
      with:
        command: rm -rf /var/www/quai-site && mv quai-site /var/www
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER}}
        key: ${{ secrets.KEY}}

    - name: Install packages, build, and start server
      uses: fifsky/ssh-action@master
      with:
        command: cd /var/www/quai-site && npm install && npm run build && HOST=0.0.0.0 PORT=8080 npm run start
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER}}
        key: ${{ secrets.KEY}}