name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Copy repository contents
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "."
        remote: var/www/quai-site
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    # - name: Copy repository contents
    #   uses: fifsky/ssh-action@master
    #   with:
    #     command: whoami
    #     host: ${{ secrets.HOST }}
    #     user: ${{ secrets.USER}}
    #     key: ${{ secrets.KEY}}

    - name: Build and start server
      uses: fifsky/ssh-action@master
      with:
        command: npm run build && HOST=0.0.0.0 PORT=8080 npm run start
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER}}
        key: ${{ secrets.KEY}}

    # - name: Copy repository contents via scp
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     source: "."
    #     target: "/var/www/quai-site"

    # - name: Executing remote command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     script: npm run build && HOST=0.0.0.0 PORT=8080 npm run start